# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch


# Create random tensor

t= torch.rand(size=(7,7))
t


tensor([[0.3035, 0.1043, 0.1054, 0.9324, 0.1976, 0.5412, 0.5111],
        [0.5578, 0.2405, 0.1066, 0.7200, 0.7326, 0.6216, 0.3717],
        [0.4389, 0.6385, 0.6367, 0.1975, 0.4781, 0.5502, 0.9164],
        [0.3424, 0.4154, 0.6709, 0.8083, 0.4879, 0.0383, 0.1786],
        [0.4084, 0.6345, 0.9772, 0.3345, 0.0692, 0.0872, 0.1274],
        [0.3628, 0.4216, 0.5354, 0.3803, 0.3272, 0.6981, 0.2450],
        [0.4620, 0.5173, 0.1281, 0.5179, 0.8101, 0.8926, 0.4372]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
t2=torch.rand(size=(1,7))
print(t2)

t3=torch.mm(t,t2.T)
t3
# Perform matrix multiplication


tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])


tensor([[1.0604],
        [1.5918],
        [1.3972],
        [0.9657],
        [0.6817],
        [1.2136],
        [1.7802]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(seed=0)


# Create two random tensors
a=torch.rand(size=(7,7))
b=torch.rand(size=(1,7))

# Matrix multiply tensors
c=torch.mm(a,b.T)
c


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
device="cuda" if torch.cuda.is_available() else "cpu"
device
torch.cuda.seed()
torch.cuda.device_count()

1


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [22]:
# Set random seed
torch.manual_seed(1234)
tensor1=torch.rand(size=(2,3)).to(device)
tensor2=torch.rand(size=(2,3)).to(device)

print(tensor1)
print(tensor2)


# Check for access to GPU

# Create two random tensors on GPU


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
tensor3=torch.mm(tensor1,tensor2.T)
tensor3


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [27]:
# Find max
torch.max(tensor3)

# Find min
torch.min(tensor3)


tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [31]:
# Find arg max
print(torch.argmax(tensor3))


# Find arg min
torch.argmin(tensor3)

tensor(3, device='cuda:0')


tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [33]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_rand=torch.rand(size=(1,1,1,10))
tensor_rand2=torch.squeeze(tensor_rand)

# Remove single dimensions


# Print out tensors and their shapes
print(tensor_rand,tensor_rand.size())
print(tensor_rand2,tensor_rand2.size())


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
